config/routes.rb
Rails.application.routes.draw do
  root to: "pins#index"
  resources :pins

  resources :follows, only:[:create, :destroy]
  resources :home
  resources :categories
  devise_for :users

  resources :users do
      member do
        get :show
      end
    end

  get '/pins/filterby/:category_id', to: "pins#filterby", as: "filter"
  post "/pins/add_comment", to: "pins#add_comment"
  post "/pins/get_info", to: "pins#get_info"

  # get 'likes/:id', to: "likes#create", as: :likes
  get 'like/:id', to: "likes#create", as: :likes
  resources :likes, only: [:destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_commentable
  acts_as_votable
  after_commit :remove_image!, on: :destroy
  belongs_to :user
  belongs_to :category, class_name: 'Category'
  mount_uploader :image, PinImageUploader
  attr_accessor :remote_pin_image_url
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :upvote, :add_comment]
  before_action :authenticate_user!, except: [:index,:show,:filterby]

  # AJAX DEMO
  # before_action :all_pins, only: [:index]
  respond_to :html, :js

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order('created_at DESC')
  end

  def filterby
    @pins = Pin.where(category_id: params[:category_id])
    @category = Category.find(params[:category_id]).name;
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @comments = @pin.comments
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def add_comment
    comment = @pin.comments.build(comment_params)
    comment.user = current_user;
    if comment.save
      redirect_to :back
    end

  end

  def get_info
    @pin = Pin.new
    @pin.pin_url = params[:pin_url];
    page = MetaInspector.new(@pin.pin_url)
    @pin.title = page.best_title
    @pin.description = page.meta['description']
    @pin.remote_image_url = page.meta['og:image']
    respond_to do |format|
      format.html { render :new }
      format.json { render json: @pin }
    end
  end

  private

    def all_pins
      @pins = Pin.all.order('created_at DESC')
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      begin
        @pin = Pin.find(params[:id])
      rescue
        redirect_to :back
      end
    end

    def comment_params
      params.permit(:comment)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :image, :remote_image_url, :pin_url,:category_id)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart: true} do |f|
  - if @pin.remote_image_url != nil
    %div.ui.segment
      %div.ui.horizontal.divider
        Image
      = image_tag (@pin.remote_image_url || ""), class: 'ui large centered image'
      = f.input :remote_image_url, label: "Image Url"
      %div.ui.horizontal.divider
        or
      = f.input :image
  - if @pin.remote_image_url == nil
    = f.input :image
    = f.input :remote_image_url, label: "Or Image url"

  = f.input :category_id, collection: Category.all, label_method: :name, value_method: :id, label: "Category",include_blank: false
  = f.input :title
  - if @pin.remote_image_url == nil
    = f.input :pin_url, label: "Reference Url"
  = f.hidden_field :pin_url, value: @pin.pin_url
  = f.input :description
  = f.button :submit
  - if @pin.remote_image_url != nil
    = link_to "Cancel", new_pin_path, class:"ui red basic button"

app/views/pins/create.js.erb
$('.ui.modal').modal('hide');
$('#pins').html("<%= j (render @pins) %>");

app/views/pins/edit.html.haml
%div.ui.two.column.centered.stackable.grid
  %div.column
    %h1
      Editing Pin
    %div.ui.segment
      = link_to 'Show', @pin, class: "tiny ui basic right floated green button"
      = image_tag @pin.image_url.to_s, class: "ui centered image"
      = render 'form', pin: @pin

app/views/pins/filterby.html.haml
%br
%div.ui.mini.floating.labeled.icon.dropdown.button
  %i.filter.icon
  %span.text
    = @category
  %div.menu
    = link_to "All", root_path, class: 'item'
    - Category.all.each do |c|
      = link_to c.name, filter_path(c.id), remote: true,data: {turbolinks: false}, class: 'item'
#pins.transitions-enabled
  = render @pins

app/views/pins/filterby.js.erb
$('#pins').html("<%= j (render @pins) %>");
board.refreshMasonry();



// $('#pins').imagesLoaded ->
//   $('#pins').masonry
//     itemSelector: '.box'
//     isFitWidth: true

app/views/pins/index.html.haml
%br
%div.ui.mini.floating.labeled.icon.dropdown.button
  %i.filter.icon
  %span.text
    Category
  %div.menu
    = link_to "All", root_path, class: 'item'
    - Category.all.each do |c|
      = link_to c.name, filter_path(c.id),remote: true, class: 'item'
#pins.transitions-enabled
  = render @pins

app/views/pins/new.html.haml
%div.ui.two.column.centered.stackable.grid
  %div.ten.wide.column
    %h1
      New Pin
    %h1
      .pinform
        = form_tag "/pins/get_info", method: "post", class: "ui reply form" do
          %label
            Pin Url
            = text_field_tag :pin_url,@pin.pin_url, placeholder:"http://"
          = submit_tag "Go", class: 'ui mini blue button'
          #cancelpinurl.ui.mini.red.button
            Cancel
    - if @pin.remote_image_url == nil
      #showpinurlbtn.ui.red.basic.button
        Pin Url
      %div.ui.horizontal.divider
        Or Create your own
      %br
    .newform
      = render 'form', pin: @pin

app/views/pins/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
// $('#task-form').slideDown(350);
$('.ui.modal')
  .modal('show')
;

app/views/pins/show.html.haml
%div.ui.segment
  = link_to (image_tag @pin.image_url.to_s, :class => "ui fluid image"), @pin.pin_url, target: "_blank"
  %div.ui.horizontal.divider
    by :
    = @pin.user.email
#like
  = render 'likes/form', likeable: @pin
- if user_signed_in? && @pin.user.email == current_user.email
  = link_to "Delete", @pin, method: :delete, data: { confirm: "Are you sure?"},:class => "ui mini right floated basic red button"
  = link_to "Edit", edit_pin_path(@pin), :class => 'ui mini right floated green button'
= link_to "Visit", @pin.pin_url, target: "_blank", :class => "ui mini right floated basic red button"



-# %div.ui.two.column.centered.stackable.grid
-#   %div.ten.wide.column
-#     %h1.ui.header
-#       = @pin.title
-#     %p.ui.description= @pin.description
-#     %div.ui.comments
-#       = render 'comments/form'
-#       %h3.ui.dividing.header
-#         Comments
-#       - @pin.comments.each do |comment|
-#         %div.comment
-#           %a.avatar
-#             %img{src: @pin.image.thumb.url}
-#           %div.content
-#             %a.author
-#               = comment.user.email
-#             %div.text
-#               = comment.comment
-#             %div.actions
-#               %a.reply
-#                 Delete

%div.ui.two.column.centered.stackable.grid
  %div.ten.wide.column
    %h1.ui.header
      = @pin.title
    %p.ui.description= @pin.description
    %div.ui.comments
      = render 'comments/form'
      %h3.ui.dividing.header
        Comments
      #comments
        = render(@comments)