config/routes.rb
Rails.application.routes.draw do
  root to: "pins#index"
  resources :pins

  resources :follows, only:[:create, :destroy]
  resources :home
  resources :categories
  devise_for :users

  resources :users do
      member do
        get :show
      end
    end

  get '/pins/filterby/:category_id', to: "pins#filterby", as: "filter"
  post "/pins/add_comment", to: "pins#add_comment"
  post "/pins/get_info", to: "pins#get_info"

  # get 'likes/:id', to: "likes#create", as: :likes
  get 'like/:id', to: "likes#create", as: :likes
  resources :likes, only: [:destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pin, only: [:create]
  respond_to :js

  def create
    @comment = @pin.comments.build(comment_params)
    @comment.user = current_user;
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy;
  end

  private
  def comment_params
    params.permit(:comment)
  end

  def set_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
%div.comment{id: comment.id}
  %a.avatar
    -# %img{src: @pin.image.thumb.url}
  %div.content
    %a.author
      = link_to comment.user.email, user_path(comment.user)
    %div.text
      = comment.comment
    %div.actions
      - if comment.user == current_user
        = link_to comment_path(comment), method: :delete, remote: true, data: {confirm: "Are you sure?"}, :class => 'reply' do
          Delete

app/views/comments/_form.html.haml
%h1
  = form_tag comments_path, method: "post", remote: true, class: "ui reply form", id: "commentform" do
    = hidden_field_tag "id", @pin.id
    = text_field_tag :comment, nil,placeholder: "write you comment"
    = submit_tag "Comment", class: 'ui mini floated blue button'

app/views/comments/create.js.erb
$("#comments").prepend("<%=j render(@comment) %>");
$("#commentform")[0].reset();

app/views/comments/destroy.js.erb
$("#<%= @comment.id %>").remove();