config/routes.rb
Rails.application.routes.draw do
  root to: "pins#index"
  resources :pins

  resources :follows, only:[:create, :destroy]
  resources :home
  resources :categories
  devise_for :users

  resources :users do
      member do
        get :show
      end
    end

  get '/pins/filterby/:category_id', to: "pins#filterby", as: "filter"
  post "/pins/add_comment", to: "pins#add_comment"
  post "/pins/get_info", to: "pins#get_info"

  # get 'likes/:id', to: "likes#create", as: :likes
  get 'like/:id', to: "likes#create", as: :likes
  resources :likes, only: [:destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pins
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/pin.rb
class Pin < ApplicationRecord
  acts_as_commentable
  acts_as_votable
  after_commit :remove_image!, on: :destroy
  belongs_to :user
  belongs_to :category, class_name: 'Category'
  mount_uploader :image, PinImageUploader
  attr_accessor :remote_pin_image_url
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_voter
  has_many :pins
  has_many :comments

  acts_as_followable
  acts_as_follower

  def self.all_except(user)
    where.not(id: user)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pin, only: [:create]
  respond_to :js

  def create
    @comment = @pin.comments.build(comment_params)
    @comment.user = current_user;
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy;
  end

  private
  def comment_params
    params.permit(:comment)
  end

  def set_pin
    @pin = Pin.find(params[:id])
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  respond_to :js

  def create
    @user = User.find(params[:format])
    current_user.follow(@user)
  end

  def destroy
    @user = User.find(params[:id])
    current_user.stop_following(@user)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @pins = current_user.pins
    @user = current_user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pin
  respond_to :js

  def create
    @pin.upvote_by current_user
  end

  def destroy
    @pin.unvote_by current_user
  end

  private

  def set_pin
      @pin = Pin.find(params[:id])
  end


  def pin_params
    params.require(:pin).permit(:title, :description, :image, :remote_image_url, :pin_url)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy, :upvote, :add_comment]
  before_action :authenticate_user!, except: [:index,:show,:filterby]

  # AJAX DEMO
  # before_action :all_pins, only: [:index]
  respond_to :html, :js

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order('created_at DESC')
  end

  def filterby
    @pins = Pin.where(category_id: params[:category_id])
    @category = Category.find(params[:category_id]).name;
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @comments = @pin.comments
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def add_comment
    comment = @pin.comments.build(comment_params)
    comment.user = current_user;
    if comment.save
      redirect_to :back
    end

  end

  def get_info
    @pin = Pin.new
    @pin.pin_url = params[:pin_url];
    page = MetaInspector.new(@pin.pin_url)
    @pin.title = page.best_title
    @pin.description = page.meta['description']
    @pin.remote_image_url = page.meta['og:image']
    respond_to do |format|
      format.html { render :new }
      format.json { render json: @pin }
    end
  end

  private

    def all_pins
      @pins = Pin.all.order('created_at DESC')
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      begin
        @pin = Pin.find(params[:id])
      rescue
        redirect_to :back
      end
    end

    def comment_params
      params.permit(:comment)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :description, :image, :remote_image_url, :pin_url,:category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show]

  def show
    @pins = @user.pins
  end

  def index
    @users = User.all_except(current_user)
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title Pinboard
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    %div.ui.top.fixed.mini.menu
      %div.ui.container
        %div.item
          = link_to "TuneXS", root_path, class: "ui circular google plus icon button"
        %div.right.menu
        - if user_signed_in?
          %div.item
            = link_to "New", new_pin_path, class: "ui basic green button"
          %div.item
            -# = link_to home_index_path, class: "ui circular facebook icon button" do
            -#   %i.user.icon
            -# %div.ui.labeled.button
            = link_to home_index_path, class: "ui labeled button" do
              %div.ui.mini.icon.orange.button
                %i.user.icon
              %div.ui.basic.label
                = current_user.email
        - else
          %div.item
            = link_to "Sign In", new_user_session_path, class: "ui basic blue button"
          %div.item
            = link_to "Sign Up", new_user_registration_path, class: "ui basic grey button"
    #content
      %div.ui.container
        - flash.each do |name, msg|
          %div.ui.info.message
            = msg
        =yield


-#         <div class="ui floating labeled icon dropdown button">
-#   <i class="filter icon"></i>
-#   <span class="text">Filter</span>
-#   <div class="menu">
-#     <div class="header">
-#       Search Issues
-#     </div>
-#     <div class="ui left icon input">
-#       <i class="search icon"></i>
-#       <input type="text" name="search" placeholder="Search...">
-#     </div>
-#     <div class="header">
-#       <i class="tags icon"></i>
-#       Filter by tag
-#     </div>
-#     <div class="divider"></div>
-#     <div class="item">
-#       <div class="ui red empty circular label"></div>
-#       Important
-#     </div>
-#     <div class="item">
-#       <div class="ui blue empty circular label"></div>
-#       Announcement
-#     </div>
-#     <div class="item">
-#       <div class="ui black empty circular label"></div>
-#       Discussion
-#     </div>
-#   </div>
-# </div>

app/views/shared/_pin.html.haml
%div.box
  %div.ui.centered.raised.card
    %div.image
      = link_to (image_tag pin.image_url.to_s, class: "ui image fluid"), pin
    %div.content
      %div.meta
        = pin.title

app/views/shared/_stats.html.haml
#stats
  %div.ui.statistics
    %div.blue.statistic
      %div.value
        = pins.count
      %div.label
        Tunes
    %div.red.statistic
      %div.value
        = user.followers.count
      %div.label
        Followers
    %div.orange.statistic
      %div.value
        = user.follows.count
      %div.label
        Following